[package]
name = "winquick"
version = "0.3.0"
edition = "2021"
description = "Run commands inside a real, disposable Windows environment"
repository = "https://github.com/carlbomsdata/winquick"
homepage = "https://github.com/carlbomsdata/winquick"
readme = "README.md"
keywords = ["windows", "macos", "virtualization", "testing"]
license = "Apache-2.0"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
fatfs = "0.3"
fscommon = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
strip = true
opt-level = "z"
lto = true
